# Generated by Django 5.2.6 on 2025-09-22 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_portfolio_alter_student_major_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Portfolio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='portfolio_app.portfolio'),
        ),
    ]
