# Generated by Django 5.2.6 on 2025-10-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_student_portfolio'),
    ]

    operations = [
    ]
